name: Build and Package

on: push

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'myapp/pom.xml'

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Maven Version Bump Action
      uses: nnichols/maven-version-bump-action@v3
      with: 
        pom-path: myapp

    - name: Build
      run: mvn clean compile

    - name: Package
      run: mvn package

    - name: Create artifact item
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target/my-artifact.jar
