name: Build and Package

on: push

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'myapp/pom.xml'

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Install XMLStarlet
      run: sudo apt-get install xmlstarlet

    - name: Change JAR version in pom.xml
      run: |
        xmlstarlet ed --inplace -u "/project/build/plugins/plugin[artifactId='maven-jar-plugin']/version" -v "1.0.0" myapp/pom.xml
        git commit -am "Update JAR version in pom.xml"
        git push

    - name: Build
      run: mvn clean compile

    - name: Package
      run: mvn package

    - name: Create artifact item
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target/my-artifact.jar
