name: Build and Package

on: push

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Increase version
      run: |
        sed -i 's/<version>1.0.0<\/version>/<version>1.0.1<\/version>/' pom.xml
        git commit -a -m "Bump version to 1.0.1" || true
        git push

    - name: Build
      run: mvn clean compile

    - name: Package
      run: mvn package

    - name: Create artifact item
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target/my-artifact.jar
