name: Build and Package

on: push

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'myapp/pom.xml'

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Increase minor version
      run: |
        # Get the current version
        version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

        # Increase the minor version by one
        new_version=$(echo $version | awk -F. '{$NF = $NF + 1; OFS="."; print $0}')

        # Update the POM file with the new version
        mvn versions:set -DnewVersion=$new_version

    - name: Build
      run: mvn clean compile

    - name: Package
      run: mvn package

    - name: Create artifact item
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target/my-artifact.jar
